#!/usr/bin/expect

set timeout 15
set host [lindex $argv 0]
set username [lindex $argv 1]
set password [lindex $argv 2]
set cmd [lindex $argv 3]

spawn ssh "$username@$host" "$cmd"

  expect {
      "(yes/no)?"
          {
              send "yes\n"
              expect "*assword:" { send "$password\n"}
	      exp_continue
          }
      "*assword:"
          {
              send "$password\n"
		exp_continue
          }
      }
#expect eof

remote_cmd.exp
#!/usr/bin/sh

#example ./fileScp.sh IP(XXXXX) name
./remote_cmd.exp $1 root pwd "useradd -m LookAlike"
./remote_cmd.exp $1 root pwd " echo pwd1 | passwd --stdin LookAlike"
echo pwd1 | ssh-copy-id -i LookAlike@$2
scp -r /home/LookAlike/* LookAlike@$2:~/
scp ~/.bashrc LookAlike@$2:~/





